# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  doc:
    desc: Update module document
    cmds:
      - v doc -o docs/ -f markdown .
      - mv docs/index.md docs/vdotenv.md

  test:
    desc: Run test
    cmds:
      - cp testdata/.env testdata/.env.parse .
      - v test vdotenv_test.v
      - task: clean

  vet:
    desc: Report suspicious code constructs
    cmds:
      - v vet *.v

  format:
    desc: Format .v files
    cmds:
      - v fmt -w *.v

  clean:
    desc: Clean repository
    cmds:
      - rm .env .env.parse
