name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - uses: actions/checkout@v4

      - name: Tests
        run: |
          cp testdata/.env testdata/.env.parse .
          v test vdotenv_test.v

      - name: Format
        run: v fmt -verify .

      - name: Lint
        run: v vet -W .

